version: '3'

services:

    #PHP Service
    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        image: php:8.3.1-fpm
        container_name: laravel.blog.php
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini

    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: laravel.blog.nginx
        tty: true
        ports:
            - "3434:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/

    #MySQL Service
    db:
        image: mysql:8.2.0
        container_name: laravel.blog.mysql
        command: "--default-authentication-plugin=mysql_native_password"
        tty: true
        ports:
            - "3435:3306"
        environment:
            MYSQL_DATABASE: blog
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker/mysql/data:/var/lib/mysql/
